// generated by "sampctl package generate"
#include "virtual-canvas.inc"

#include <a_samp>

main() {
	new canvas[VirtualCanvas], Float:x, Float:y;

	CreateVirtualCanvas(-3000.0, 3000.0, -3000.0, 3000.0, 1000, 1000, canvas);
	GetVirtualCanvasPos(canvas, 500, 500, x, y);
	printf("%f %f", x, y); // 0, 0, centre of map

	CreateVirtualCanvas(-3000.0, 3000.0, -3000.0, 3000.0, 1000, 1000, canvas);
	GetVirtualCanvasPos(canvas, 750, 750, x, y);
	printf("%f %f", x, y); // 1500, 1500, north east quadrant

	CreateVirtualCanvas(-3000.0, 3000.0, -3000.0, 3000.0, 1000, 1000, canvas);
	GetVirtualCanvasPos(canvas, 250, 750, x, y);
	printf("%f %f", x, y); // -1500, 1500, south east quadrant

	CreateVirtualCanvas(0.0, 3000.0, 0.0, 3000.0, 1000, 1000, canvas);
	GetVirtualCanvasPos(canvas, 500, 500, x, y);
	printf("%f %f", x, y); // 1500, 1500, north east quadrant
}
